// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TangyAPI.Data;

#nullable disable

namespace TangyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620102345_SeedCategories")]
    partial class SeedCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TangyAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedOn = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Entree"
                        },
                        new
                        {
                            Id = 2,
                            AddedOn = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Appetiser"
                        },
                        new
                        {
                            Id = 3,
                            AddedOn = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Desert"
                        },
                        new
                        {
                            Id = 4,
                            AddedOn = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Starter"
                        },
                        new
                        {
                            Id = 5,
                            AddedOn = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snaks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
